### ISSUE TITLE
Snapshot/Archive fails

### ISSUE THREAD

**Issue by hilsonshrestha** [revisit-studies/study#434] opened 2024-07-19 15:33 UTC
In `FirebaseStorageEngine.ts`, the `_directoryExists` method always return false in some studies.

![image](https://github.com/user-attachments/assets/ce692f8e-dc07-4132-89c1-055bc9216e66)

**Comment by bbollen23** [comment] 2024-08-01 20:38
Couple notes on this:
1. If the _sequenceArray file is missing, the snapshot will fail. This is by design since, it shouldn't have any data if there is no sequenceArray. I'm opening a separate issue to check for errors when trying to create snapshots
2. @hilsonshrestha experienced an issue with snapshots deleting the _sequenceArray, but we cannot recreate the bug. Everything is now working as expected with no change.

I'm closing this for now until we notice this issue again where we can further debug.

**Closed by bbollen23** 2024-08-01 20:38 UTC
